mon_site/src/Entity/RERNG.php
<?php

namespace App\Entity;

use App\Repository\RERNGRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RERNGRepository::class)
 */
class RERNG
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Rames;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $motrices;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $mise_en_service;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $livree;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_de_caisses;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $stf;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $radiation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $equipements_interieurs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lignes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRames(): ?string
    {
        return $this->Rames;
    }

    public function setRames(string $Rames): self
    {
        $this->Rames = $Rames;

        return $this;
    }

    public function getMotrices(): ?string
    {
        return $this->motrices;
    }

    public function setMotrices(string $motrices): self
    {
        $this->motrices = $motrices;

        return $this;
    }

    public function getMiseEnService(): ?\DateTimeInterface
    {
        return $this->mise_en_service;
    }

    public function setMiseEnService(\DateTimeInterface $mise_en_service): self
    {
        $this->mise_en_service = $mise_en_service;

        return $this;
    }

    public function getLivree(): ?string
    {
        return $this->livree;
    }

    public function setLivree(string $livree): self
    {
        $this->livree = $livree;

        return $this;
    }

    public function getNombreDeCaisses(): ?int
    {
        return $this->nombre_de_caisses;
    }

    public function setNombreDeCaisses(int $nombre_de_caisses): self
    {
        $this->nombre_de_caisses = $nombre_de_caisses;

        return $this;
    }

    public function getStf(): ?string
    {
        return $this->stf;
    }

    public function setStf(string $stf): self
    {
        $this->stf = $stf;

        return $this;
    }

    public function getRadiation(): ?\DateTimeInterface
    {
        return $this->radiation;
    }

    public function setRadiation(\DateTimeInterface $radiation): self
    {
        $this->radiation = $radiation;

        return $this;
    }

    public function getEquipementsInterieurs(): ?string
    {
        return $this->equipements_interieurs;
    }

    public function setEquipementsInterieurs(string $equipements_interieurs): self
    {
        $this->equipements_interieurs = $equipements_interieurs;

        return $this;
    }

    public function getLignes(): ?string
    {
        return $this->lignes;
    }

    public function setLignes(string $lignes): self
    {
        $this->lignes = $lignes;

        return $this;
    }
}

mon_site/src/Form/RERNGType.php
<?php

namespace App\Form;

use App\Entity\RERNG;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class RERNGType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Rames')
            ->add('motrices')
            ->add('mise_en_service', DateType::class, [
                'widget'=> 'single_text',
                'input_format'=> 'd/m/Y',
            ])
            ->add('livree', ChoiceType::class, [
                'choices' => [
                    '--Choissisez une livrée--' => [
                        'Ile-de-France Mobilités' => 'Ile-de-France Mobilités',

                    ],

                ],
                
            ])
            ->add('nombre_de_caisses')
            ->add('stf')
            ->add('radiation' , DateType::class, [
                'widget'=> 'single_text',
                'input_format'=> 'd/m/Y',
            ])
            ->add('equipements_interieurs',ChoiceType::class, [
                'choices' => [
                    '--Choissisez les équipements intérieurs--' => [
                        'SIVE - vidéosurveillance' => 'SIVE - vidéosurveillance',
                        
                        

                    ],

                ],
                
            ])
            ->add('lignes',ChoiceType::class, [
                'choices' => [
                    '--Choissisez une ou plusieurs ligne(s)--' => [
                        'RER D' => 'RER D',
                        'RER E' => 'RER E',
                        'En essai' => 'En essai',
                        

                    ],

                ],
                
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RERNG::class,
        ]);
    }
}

mon_site/src/Controller/RERNGController.php
<?php

namespace App\Controller;

use App\Entity\RERNG;
use App\Form\RERNGType;
use App\Repository\RERNGRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



/**
     * @Route("/rerng")
     */
class RERNGController extends AbstractController
{
    
    /**
     * @Route("/", name="rerng", methods={"GET"})
     */
    public function index(RERNGRepository $rERNGRepository): Response
    {
        return $this->render('rerng/rerng.html.twig', [
            'r_e_r_n_gs' => $rERNGRepository->findAll(),
            
        ]);
    }

    /**
     * @Route("/new", name="rerng_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rERNG = new RERNG();
        $form = $this->createForm(RERNGType::class, $rERNG);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rERNG);
            $entityManager->flush();
            

            return $this->redirectToRoute('rerng', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rerng/new.html.twig', [
            'rerng' => $rERNG,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="rerng_show", methods={"GET"})
     */
    public function show(RERNG $rERNG): Response
    {
        return $this->render('rerng/show.html.twig', [
            'rerng' => $rERNG,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rerng_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RERNG $rERNG): Response
    {
        $form = $this->createForm(RERNGType::class, $rERNG);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rerng', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rerng/edit.html.twig', [
            'rerng' => $rERNG,
            'form' => $form,
        ]);
    }

   /**
     * @Route("/{id}", name="rerng_delete", methods={"POST"})
     */
    public function delete(Request $request, RERNG $rERNG): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rERNG->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rERNG);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rerng', [], Response::HTTP_SEE_OTHER);
    }
}

mon_site/templates/rerng/_delete_form.html.twig
<form method="post" action="{{ path('rerng_delete', {'id': rerng.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cette rame ? 😐');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rerng.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

mon_site/templates/rerng/edit.html.twig
{% include 'head.html' %}
<body>
{% block title %}{% endblock %}

{% block body %}
<div class="container">
<div class="form-group">

    <h1>Editer une rame</h1>

    

    {{ include('rerng/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    </div>
<div class="retournerliste">
    <a class="btn btn-secondary" href="{{ path('rerng') }}">Revenir à la liste</a>

</div>
    {{ include('rerng/_delete_form.html.twig') }}
    </div>
    
{% endblock %}

</body>


</html>

mon_site/templates/rerng/new.html.twig
{% include 'head.html' %}


{% block title %}{% endblock %}

{% block body %}
<div class="container">
<h1>Ajouter une nouvelle rame</h1>
<div class="form-group">

    
    

    

    {{ include('rerng/_form.html.twig') }}
    </div>
    <div class="retournerliste">

    <a class="btn btn-secondary" href="{{ path('rerng') }}">Revenir à la liste</a>
    </div>
    </div>
{% endblock %}

mon_site/templates/rerng/rerng.html.twig
{% include 'head.html' %}



    <body>

    <header>
{% include 'nav.html.twig' %}
<div class="jumbotron">
            <h1 class="display-4">Les RERNG</h1>
            <img src="{{ asset('/rerng_juvisy.jpg') }}" class="my-6 " style="width: 500px;" alt="RERNG faisant une pause à Juvisy"> 
            
        
        <div class="container">
        <hr class="my-4">
        <article>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti nobis at omnis molestiae doloribus eos reprehenderit laudantium qui tempore a. Earum amet velit et adipisci eos, animi voluptatum suscipit dolore.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur et totam est velit dolores saepe dignissimos eligendi provident similique, voluptate temporibus. Dicta debitis, vitae quos cum beatae cumque veritatis quae?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis minus illum in aspernatur, ex nisi at perspiciatis voluptatibus debitis eius voluptatem accusamus, unde, tempora nemo aut! Quos placeat minima quam.
        </article>
        </div>
       
    </div>
        </header>

<main>

{% block body %}
    <h1>Etat du matériel</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Rames</th>
                <th>Motrices</th>
                <th>Mise_en_service</th>
                <th>Livree</th>
                <th>Nombre_de_caisses</th>
                <th>Stf</th>
                <th>Radiation</th>
                <th>Equipements_interieurs</th>
                <th>Lignes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for r_e_r_n_g in r_e_r_n_gs %}
            <tr>
                <td>{{ r_e_r_n_g.Rames }}</td>
                <td>{{ r_e_r_n_g.motrices }}</td>
                <td>{{ r_e_r_n_g.miseEnService ? r_e_r_n_g.miseEnService|date('d-m-Y') : '' }}</td>
                <td>{{ r_e_r_n_g.livree }}</td>
                <td>{{ r_e_r_n_g.nombreDeCaisses }}</td>
                <td>{{ r_e_r_n_g.stf }}</td>
                <td>{{ r_e_r_n_g.radiation ? r_e_r_n_g.radiation|date('d-m-Y') : '' }}</td>
                <td>{{ r_e_r_n_g.equipementsInterieurs }}</td>
                <td>{{ r_e_r_n_g.lignes }}</td>
                <td>
    

                    <a class="btn btn-warning btn-sm" href="{{ path('rerng_show', {'id': r_e_r_n_g.id}) }}">Voir</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a class="btn btn-info" href="{{ path('rerng_edit', {'id': r_e_r_n_g.id}) }}">Editer</a>
                    {% endif %}
                    <button type="button" class="btn btn-dark btn-sm">❤</button>
                </td>
            </tr>
        {% else %}
            <div class="notfound"
            <tr>
            
                <td colspan="11">Aucune rame 😢</td>
                </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted('ROLE_ADMIN') %}
    <a class="btn btn-success" href="{{ path('z5600_new') }}">Ajouter une rame +</a>
    {% endif %}
{% endblock %}
</main>
{% include 'footer.html' %}

        
        

        </body>
        </html>

mon_site/templates/rerng/show.html.twig
{% block title %}RERNG{% endblock %}

{% block body %}
    <h1>RERNG</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ r_e_r_n_g.id }}</td>
            </tr>
            <tr>
                <th>Rames</th>
                <td>{{ r_e_r_n_g.Rames }}</td>
            </tr>
            <tr>
                <th>Motrices</th>
                <td>{{ r_e_r_n_g.motrices }}</td>
            </tr>
            <tr>
                <th>Mise_en_service</th>
                <td>{{ r_e_r_n_g.miseEnService ? r_e_r_n_g.miseEnService|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Livree</th>
                <td>{{ r_e_r_n_g.livree }}</td>
            </tr>
            <tr>
                <th>Nombre_de_caisses</th>
                <td>{{ r_e_r_n_g.nombreDeCaisses }}</td>
            </tr>
            <tr>
                <th>Stf</th>
                <td>{{ r_e_r_n_g.stf }}</td>
            </tr>
            <tr>
                <th>Radiation</th>
                <td>{{ r_e_r_n_g.radiation ? r_e_r_n_g.radiation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Equipements_interieurs</th>
                <td>{{ r_e_r_n_g.equipementsInterieurs }}</td>
            </tr>
            <tr>
                <th>Lignes</th>
                <td>{{ r_e_r_n_g.lignes }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rerng') }}">back to list</a>

    <a href="{{ path('rerng_edit', {'id': r_e_r_n_g.id}) }}">edit</a>

    {{ include('rerng/_delete_form.html.twig') }}
{% endblock %}