mon_site/src/Entity/Realisation.php
<?php

namespace App\Entity;

use App\Repository\RealisationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=RealisationRepository::class)
 *  @Vich\Uploadable
 */
class Realisation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_image;

    /**
     * @ORM\Column(type="date")
     */
    private $date_publication;

    /**
     * @ORM\Column(type="text")
     */
    private $description_image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

     /**
     * @Vich\UploadableField(mapping="realisation_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @var string
     * 
     * @Gedmo\Slug(fields={"nom_image"})
     * 
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Auteur::class, inversedBy="realisations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Auteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    

    public function getNomImage(): ?string
    {
        return $this->nom_image;
    }

    public function setNomImage(string $nom_image): self
    {
        $this->nom_image = $nom_image;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getDescriptionImage(): ?string
    {
        return $this->description_image;
    }

    public function setDescriptionImage(string $description_image): self
    {
        $this->description_image = $description_image;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->Auteur;
    }

    public function setAuteur(?Auteur $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }
    

}

mon_site/src/Form/RealisationType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use App\Entity\Realisation;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use phpDocumentor\Reflection\DocBlock\DescriptionFactory;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class RealisationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('auteur', EntityType::class, [
            'class' => Auteur::class,
            'choice_label' => 'prenom'
         ])
            ->add('imageFile', FileType::class, [
                'required' => true,
               ])
            ->add('date_publication', DateType::class, [
                'widget'=> 'single_text',
                'input_format'=> 'd/m/Y',
                'label'=> 'Date de publication: '
                
            ])
            ->add('description_image', TextareaType::class, [
                'label'=>' Description: ',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Realisation::class,
        ]);
    }
}

mon_site/src/Controller/RealisationController.php
<?php

namespace App\Controller;

use App\Entity\Realisation;
use App\Form\RealisationType;
use App\Repository\RealisationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
     * @Route("realisation")
     */
class RealisationController extends AbstractController
{
    /**
     * @Route("/realisation", name="realisation", methods={"GET"})
     */
    public function index(RealisationRepository $realisationRepository): Response
    {
        return $this->render('realisation/realisation.html.twig', [
            'realisations' => $realisationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="realisation_new", methods={"GET","POST"})
     */
    public function new(Request $request, KernelInterface $kernel): Response
    {
        $realisation = new Realisation();
        $form = $this->createForm(RealisationType::class, $realisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photos = $form->get('photo')->getData();
            foreach ($photos as $photo) {
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $photo->guessExtension();
                $photo->move(
                    $imagesDir = $kernel->getProjectDir().'/public/uploads/images',
                    $fichier
                );

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($realisation);
            $entityManager->flush();

            return $this->redirectToRoute('realisation', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('realisation/new.html.twig', [
            'realisation' => $realisation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="realisation_show", methods={"GET"})
     */
    public function show(Realisation $realisation): Response
    {
        return $this->render('realisation/show.html.twig', [
            'realisation' => $realisation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="realisation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Realisation $realisation): Response
    {
        $form = $this->createForm(RealisationType::class, $realisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('realisation', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('realisation/edit.html.twig', [
            'realisation' => $realisation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="realisation_delete", methods={"POST"})
     */
    public function delete(Request $request, Realisation $realisation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$realisation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($realisation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('realisation', [], Response::HTTP_SEE_OTHER);
    }
}

mon_site/templates/realisation/_delete_form.html.twig
<form method="post" action="{{ path('realisation_delete', {'id': realisation.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cette rame ? 😐');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ realisation.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

mon_site/templates/realisation/edit.html.twig
<html>
{% include 'head.html' %}
	<body>

		<header>
			{% include 'nav.html.twig' %}
            </header>

{% block title %}{% endblock %}

{% block body %}
<div class="container">
    <h1>Editer une photo</h1>
    <div class="form-group">

    {{ include('realisation/_form.html.twig', {'button_label': 'Sauvegarder'}) }}
</div>
    <a class="btn btn-secondary" href="{{ path('realisation') }}">Retourner à la liste</a>

    {{ include('realisation/_delete_form.html.twig') }}
    </div>
    </div>
{% endblock %}


</body>
</html>

mon_site/templates/realisation/new.html.twig
<html>
{% include 'head.html' %}
<body>

<header>
{% include 'nav.html.twig' %}
</header>
{% block title %}{% endblock %}

{% block body %}
<div class="container">

    <h1>Ajouter une nouvelle photo</h1>
<div class="form-group">
    {{ include('realisation/_form.html.twig') }}
</div>
<div class="retournerliste">
    <a class="btn btn-secondary" href="{{ path('realisation') }}">Retourner à la liste</a>
    </div>
    </div>
{% endblock %}





</body>
</html>

mon_site/templates/realisation/realisation.html.twig
<html>
	{% include 'head.html' %}
	<body>

		<header>
			{% include 'nav.html.twig' %}
		</header>


		<link
		rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">


		<!-- Bootstrap core CSS -->
		<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

		<style>
			.bd-placeholder-img {
				font-size: 1.125rem;
				text-anchor: middle;
				-webkit-user-select: none;
				-moz-user-select: none;
				user-select: none;
			}

			@media(min-width: 768px) {
				.bd-placeholder-img-lg {
					font-size: 3.5rem;
				}
			}
		</style>
	</body>
</html></head><body>


<main>

	<section class="py-5 text-center container">
		<div class="row py-lg-5">
			<div class="col-lg-6 col-md-8 mx-auto">
				<h1 class="fw-light">Mes réalisations</h1>
				<p class="lead text-muted">Voici ma galerie photo où j'y posterai régulièrement des créations récentes ainsi que des archives.</p>
			</div>
		</div>
	</section>

	<div class="album py-5 bg-light">
		<div class="container">

			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
				{% for realisation in realisations %}
					<div class="col">
						<div class="card shadow-sm">
							<img class="bd-placeholder-img card-img-top" id="img-responsive" src="{{ asset(realisation.photo) }}" width="100%" height="225">

							<div class="card-body">
								<h4 class="card-title">
									{{ realisation.nomImage }}
								</h4>
								<p class="card-text">Publié par
									{{ realisation.auteur }}
									le
									{{ realisation.datePublication ? realisation.datePublication|date('d-m-Y') : '' }}</p>
								<text class="card-text">{{ realisation.descriptionImage }}</text>
							</div>
						</div>
					</div>
					
				{% endfor %}
				
			</main>
			<footer class="text-muted py-5">
				<div class="container">
					<p class="float-end mb-1">
						<a class="btn btn-sm btn-primary" href="#">Retourner en haut</a>
					</p>
					<p class="mb-1 py-4">2021 &copy; 91xwriter - Alexandre Diakité</p>
				</div>
			</footer>


			<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>


		</body>
	</html>

mon_site/templates/realisation/show.html.twig
<html>
{% include 'head.html' %}
	<body>

		<header>
			{% include 'nav.html.twig' %}
            </header>

{% block title %}{% endblock %}

{% block body %}
<div class="container">
    <h1>Mes réalisations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ realisation.id }}</td>
            </tr>
            <tr>
                <th>Auteur</th>
                <td>{{ realisation.auteur }}</td>
            </tr>
            <tr>
                <th>Nom de l'image</th>
                <td>{{ realisation.nomImage }}</td>
            </tr>
            <tr>
                <th>Date de publication</th>
                <td>{{ realisation.datePublication ? realisation.datePublication|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ realisation.descriptionImage }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ realisation.photo }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-secondary" href="{{ path('realisation') }}">Retourner à la liste</a>

    <a class="btn btn-info" href="{{ path('realisation_edit', {'id': realisation.id}) }}">Editer</a>

    {{ include('realisation/_delete_form.html.twig') }}
    </div>
{% endblock %}